/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import Controller.CadastroJogadorController;
import DAO.JogadorDAO;
import controle.Conta;
import controle.Pessoa;
import controle.Jogador;
import controle.Contato;
import controle.Endereco;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.text.resources.FormatData;

/**
 *
 * @author laiender.morais
 */
public class CadastroJogador extends javax.swing.JFrame {

    boolean atualizar = true;

    /**
     * Creates new form cadastro
     */
    public CadastroJogador() {
        initComponents();

        Atualizar.setEnabled(false);
        Excluir.setEnabled(false);
        HabilitarCampos.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        estado = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        indentidade = new javax.swing.JTextField();
        escolaridade = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        instituicao = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sobreNome = new javax.swing.JTextField();
        nacionalidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dddFixo = new javax.swing.JTextField();
        telefoneFixo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        posicao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        dddCelular = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        complemento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        pais = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        categoria = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nomeEmpresario = new javax.swing.JTextField();
        dataNascimento = new javax.swing.JFormattedTextField();
        InformacoesMedicas = new javax.swing.JButton();
        Contrato = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        HabilitarCampos = new javax.swing.JButton();
        idPessoa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Jogador");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome:");

        nome.setColumns(2);
        nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de Nascimento:");

        jLabel6.setText("E-mail:");

        estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Minas Gerais", "São Paulo", "Rio de Janeiro", "Espeito Santo" }));

        jLabel9.setText("Estado:");

        jLabel24.setText("Indentidade:");

        indentidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indentidadeActionPerformed(evt);
            }
        });

        jLabel26.setText("Escolaridade:");

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        jLabel25.setText("CPF:");

        jLabel27.setText("Intituição:");

        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });

        jLabel10.setText("Cidade:");

        jLabel11.setText("Rua:");

        sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculono", "Feminino" }));

        jLabel4.setText("Sexo:");

        jLabel2.setText("Sobrenome:");

        jLabel5.setText("Nasionalidade:");

        jLabel7.setText("Telefone:");

        jLabel12.setText("Numero:");

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });

        jLabel28.setText("Peso:");

        jLabel29.setText("Posição:");

        posicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicaoActionPerformed(evt);
            }
        });

        jLabel13.setText("Bairro:");

        jLabel8.setText("Celular:");

        jLabel30.setText("Altura:");

        complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementoActionPerformed(evt);
            }
        });

        jLabel14.setText("Complemento:");

        jLabel15.setText("CEP:");

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        jLabel16.setText("Pais:");

        pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Categoria:");

        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });

        jLabel18.setText("Empresario:");

        dataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicao, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(indentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dddCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeEmpresario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Voltar)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(376, 376, 376)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sobreNome))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dddFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(telefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 138, Short.MAX_VALUE)))
                                .addGap(172, 172, 172))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(instituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(categoria)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(528, 528, 528))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(dddFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dddCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(indentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(instituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(posicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Voltar)
                            .addComponent(Salvar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(nomeEmpresario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        InformacoesMedicas.setText("Informações Medicas");
        InformacoesMedicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacoesMedicasActionPerformed(evt);
            }
        });

        Contrato.setText("Contrato");
        Contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratoActionPerformed(evt);
            }
        });

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        HabilitarCampos.setText("Habilitar Campos");
        HabilitarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabilitarCamposActionPerformed(evt);
            }
        });

        idPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Contrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InformacoesMedicas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HabilitarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Excluir)
                        .addGap(13, 13, 13)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InformacoesMedicas)
                    .addComponent(Contrato)
                    .addComponent(Atualizar)
                    .addComponent(Excluir)
                    .addComponent(HabilitarCampos)
                    .addComponent(idPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        // TODO add your handling code here:
        Jogador p = new Jogador();
        JOptionPane.showMessageDialog(null, "atualizar ao salvar   " + atualizar);
        if (atualizar == true) {
            try {

                p.setNome(nome.getText());
                p.setSobreNome(sobreNome.getText());
                p.setNacionalidade(nacionalidade.getText());
                p.setSexo(((String) (sexo.getSelectedItem())));
                p.setRg(indentidade.getText());
                p.setCpf(cpf.getText());
                //SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                //data = formato.parse(dataNascimento.getDate().toString());
                //java.sql.Date datasql = new java.sql.Date(data.getTime());
                //Calendar dataNascimento= Calendar.getInstance();
                p.setDataNascimento(dataNascimento.getText());
                JOptionPane.showMessageDialog(null, "data nacsimento ao inserir" + p.getDataNascimento());
                //p.setDataNascimento(dataNascimento.setDate(new SimpleDateFormat("dd/MM/yyyy").parse((dataNascimento))));
                p.setEscolaridade(escolaridade.getText());
                p.setInstituicao(instituicao.getText());
                p.setEndereco(new Endereco(rua.getText(), numero.getText(), bairro.getText(), cidade.getText(),
                        ((String) (estado.getSelectedItem())), ((String) (pais.getSelectedItem())), complemento.getText(), cep.getText()));
                p.setContato(new Contato(telefoneFixo.getText(), celular.getText(), email.getText()));
                p.setCategoria(categoria.getText());
                p.setNomeEmpresario(nomeEmpresario.getText());

                //p.setConta(new Conta());
                p.setPosicao(posicao.getText());
                p.setPeso(Double.parseDouble(peso.getText().replace(',', '.')));
                p.setAltura(Double.parseDouble(altura.getText().replace(',', '.')));

                //LimparCampos();
                //if (atualizar== true){
                //    CadastroJogadorController.atualizar(p);
                //   JOptionPane.showMessageDialog(null, "atualizar jogador CadastroJogador.... ");
                //}else
                if (CadastroJogadorController.persistir(p) == true) {
                    JOptionPane.showMessageDialog(this, "Jogador gravado com sucesso");
                    dispose();
                }

            } catch (Exception ex) {
                Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Atualizar ao modificar  " + atualizar);
            try {
                CadastroJogadorController.atualizar(p);
                JOptionPane.showMessageDialog(null, "Cadastro atualizado...");
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        /*
            try {
                atualizarCadastro();
            } catch (ParseException ex) {
                Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
            }
         */

    }//GEN-LAST:event_SalvarActionPerformed

    public void LimparCampos() {
        nome.setText("");
        sobreNome.setText("");
        nacionalidade.setText("");
        indentidade.setText("");
        cpf.setText("");
        dataNascimento.setText("");
        escolaridade.setText("");
        instituicao.setText("");
        rua.setText("");
        numero.setText("");
        bairro.setText("");
        cidade.setText("");
        complemento.setText("");
        cep.setText("");
        categoria.setText("");
        nomeEmpresario.setText("");
        telefoneFixo.setText("");
        celular.setText("");
        email.setText("");
        posicao.setText("");
        peso.setText("");
        altura.setText("");
    }
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        TelaJogador jog = null;
        try {
            jog = new TelaJogador();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
        }
        jog.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarActionPerformed

    /*public static void preencher(Jogador jogador) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                preencherTelaJogador(jogador);
    }*/
    public void preencherTelaJogador(Jogador jogador) throws ParseException {
        //Jogador jogador = jogadorp;
        Atualizar.setEnabled(false);
        Excluir.setEnabled(true);
        idPessoa.setText(String.valueOf(jogador.getIdPessoa()));
        idPessoa.setEditable(false);
        nome.setText(jogador.getNome());
        nome.setEditable(false);
        sobreNome.setText(jogador.getSobreNome());
        sobreNome.setEditable(false);
        nacionalidade.setText(jogador.getNacionalidade());
        nacionalidade.setEditable(false);
        indentidade.setText(jogador.getRg());
        indentidade.setEditable(false);
        cpf.setText(jogador.getCpf());
        cpf.setEditable(false);
        JOptionPane.showMessageDialog(null, "Data de nascimento no preencher Tela " + jogador.getDataNascimento());
        dataNascimento.setText(jogador.getDataNascimento());
        dataNascimento.setEnabled(false);
        escolaridade.setText(jogador.getEscolaridade());
        escolaridade.setEditable(false);
        instituicao.setText(jogador.getInstituicao());
        instituicao.setEditable(false);
        telefoneFixo.setText(jogador.getContato().getTelefoneResidencial());
        telefoneFixo.setEditable(false);
        celular.setText(jogador.getContato().getCelular());
        celular.setEditable(false);
        email.setText(jogador.getContato().getEmail());
        email.setEditable(false);
        rua.setText(jogador.getEndereco().getRua());
        rua.setEditable(false);
        numero.setText(jogador.getEndereco().getNumero());
        numero.setEditable(false);
        bairro.setText(jogador.getEndereco().getBairro());
        bairro.setEditable(false);
        cidade.setText(jogador.getEndereco().getCidade());
        cidade.setEditable(false);
        complemento.setText(jogador.getEndereco().getComplemento());
        complemento.setEditable(false);
        cep.setText(jogador.getEndereco().getCep());
        cep.setEditable(false);
        categoria.setText(jogador.getCategoria());
        categoria.setEditable(false);
        nomeEmpresario.setText(jogador.getNomeEmpresario());
        nomeEmpresario.setEditable(false);
        posicao.setText(jogador.getPosicao());
        posicao.setEditable(false);
        peso.setText(String.valueOf(jogador.getPeso()));
        peso.setEditable(false);
        altura.setText(String.valueOf(jogador.getAltura()));
        altura.setEditable(false);
        sexo.setSelectedItem(jogador.getSexo());
        sexo.setEnabled(false);
        pais.setSelectedItem(jogador.endereco.getPais());
        pais.setEnabled(false);
        estado.setSelectedItem(jogador.endereco.getEstado());
        estado.setEnabled(false);
    }

    public Jogador atualizarCadastro() throws ParseException, SQLException {
        Jogador jogador = new Jogador();
        atualizar = false;
        Atualizar.setEnabled(true);
        Excluir.setEnabled(true);
        //jogador.setNome(nome.getText());
        nome.setEditable(true);
        //jogador.setSobreNome(sobreNome.getText());
        sobreNome.setEditable(true);
        //jogador.setNacionalidade(nacionalidade.getText());
        nacionalidade.setEditable(true);
        //jogador.setRg(indentidade.getText());
        indentidade.setEditable(true);
        //jogador.setCpf(cpf.getText());
        cpf.setEditable(true);
        //jogador.setDataNascimento(dataNascimento.getText());
        dataNascimento.setEnabled(true);
        //jogador.setEscolaridade(escolaridade.getText());
        escolaridade.setEditable(true);
        //jogador.setInstituicao(instituicao.getText());
        instituicao.setEditable(true);
        //jogador.setEndereco(new Endereco(rua.getText(), numero.getText(), bairro.getText(), cidade.getText(), 
        //            ((String)(estado.getSelectedItem())), ((String)(pais.getSelectedItem())), complemento.getText(), cep.getText() ));
        //jogador.setContato(new Contato( telefoneFixo.getText(),celular.getText(), email.getText()));
        //jogador.contato.setTelefoneResidencial(telefoneFixo.getText());
        telefoneFixo.setEditable(true);
        //jogador.contato.setCelular(celular.getText());
        celular.setEditable(true);
        //jogador.contato.setEmail(email.getText());
        email.setEditable(true);
        //jogador.endereco.setRua(rua.getText());
        rua.setEditable(true);
        //jogador.endereco.setNumero(numero.getText());
        numero.setEditable(true);
        //jogador.endereco.setBairro(bairro.getText());
        bairro.setEditable(true);
        //jogador.endereco.setCidade(cidade.getText());
        cidade.setEditable(true);
        //jogador.endereco.setComplemento(complemento.getText());
        complemento.setEditable(true);
        //jogador.endereco.setCep(cep.getText());
        cep.setEditable(true);
        //jogador.setCategoria(categoria.getText());
        categoria.setEditable(true);
        //jogador.setNomeEmpresario(nomeEmpresario.getText());
        nomeEmpresario.setEditable(true);
        //jogador.setPosicao(posicao.getText());
        posicao.setEditable(true);
        //jogador.setPeso(Double.parseDouble(peso.getText().replace(',', '.')));
        peso.setEditable(true);
        //jogador.setAltura(Double.parseDouble(peso.getText().replace(',', '.')));
        altura.setEditable(true);
        //jogador.setSexo((String)sexo.getSelectedItem());
        sexo.setEnabled(true);
        //jogador.endereco.setPais((String)pais.getSelectedItem());
        pais.setEnabled(true);
        //jogador.endereco.setEstado((String) estado.getSelectedItem());
        estado.setEnabled(true);

        //CadastroJogadorController.atualizar(jogador);
        //JOptionPane.showMessageDialog(this, "Jogador gravado com sucesso");
        /*try {
            CadastroJogadorController.atualizar(jogador);
            JOptionPane.showMessageDialog(this, "Jogador gravado com sucesso");
            //try {
            //atualizarCadastro(jogador);
            //CadastroJogadorController.atualizar(jogador);
            
            //JOptionPane.showMessageDialog(this, "Jogador gravado com sucesso");
            //} catch (ParseException ex) {
            //   Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
            //} catch (SQLException ex) {
            //   Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
            //}
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        //dispose();
        return jogador;

    }

    private void InformacoesMedicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacoesMedicasActionPerformed
        CadastroInformaçõesMedicas medico = new CadastroInformaçõesMedicas();
        medico.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_InformacoesMedicasActionPerformed

    private void ContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratoActionPerformed
        CadastroDeContrato contrato = new CadastroDeContrato();
        contrato.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_ContratoActionPerformed

    private void complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complementoActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void indentidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indentidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indentidadeActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void posicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicaoActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        HabilitarCampos.setEnabled(true);
        atualizar = true;
//        Jogador jogador= new Jogador();
//        jogador=atualizarCadastro();
//        JOptionPane.showMessageDialog(null, "Dados atualizados");
//        JOptionPane.showMessageDialog(null, "nome do jagador atualizado : "+ jogador.getNome());
//CadastroJogadorController.atualizar(jogador);
        Jogador jogador = new Jogador();
        /*Atualizar.setEnabled(true);
Excluir.setEnabled(true);
nome.setEditable(true);
sobreNome.setEditable(true);
nacionalidade.setEditable(true);
indentidade.setEditable(true);
cpf.setEditable(true);
dataNascimento.setEnabled(true);
escolaridade.setEditable(true);
instituicao.setEditable(true);
telefoneFixo.setEditable(true);
celular.setEditable(true);
email.setEditable(true);
rua.setEditable(true);
numero.setEditable(true);
bairro.setEditable(true);
cidade.setEditable(true);
complemento.setEditable(true);
cep.setEditable(true);
categoria.setEditable(true);
nomeEmpresario.setEditable(true);
posicao.setEditable(true);
peso.setEditable(true);
altura.setEditable(true);
sexo.setEnabled(true);
pais.setEnabled(true);
estado.setEnabled(true);*/

        jogador.setNome(nome.getText());
        jogador.setSobreNome(sobreNome.getText());
        jogador.setNacionalidade(nacionalidade.getText());
        jogador.setRg(indentidade.getText());
        jogador.setCpf(cpf.getText());
        jogador.setDataNascimento((String) dataNascimento.getText());
        jogador.setEscolaridade(escolaridade.getText());
        jogador.setInstituicao(instituicao.getText());
        jogador.setEndereco(new Endereco(rua.getText(), numero.getText(), bairro.getText(), cidade.getText(),
                ((String) (estado.getSelectedItem())), ((String) (pais.getSelectedItem())), complemento.getText(), cep.getText()));
        jogador.setContato(new Contato(telefoneFixo.getText(), celular.getText(), email.getText()));
        jogador.setCategoria(categoria.getText());
        jogador.setNomeEmpresario(nomeEmpresario.getText());
        jogador.setPosicao(posicao.getText());
        jogador.setPeso(Double.parseDouble(peso.getText().replace(',', '.')));
        jogador.setAltura(Double.parseDouble(peso.getText().replace(',', '.')));
        jogador.setSexo((String) sexo.getSelectedItem());

        try {
            CadastroJogadorController.atualizar(jogador);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AtualizarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        try {
            // TODO add your handling code here:
            int idpessoa;
            
            idpessoa=Integer.parseInt(idPessoa.getText());
            JOptionPane.showMessageDialog(null, "IdPessoa para deletar  "+ idpessoa);
            CadastroJogadorController.deletar(idpessoa);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro ao deletar  " + ex);
            Logger.getLogger(CadastroJogador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void dataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoActionPerformed

    private void HabilitarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabilitarCamposActionPerformed
        atualizar = true;
        Atualizar.setEnabled(true);
        Excluir.setEnabled(true);
        nome.setEditable(true);
        sobreNome.setEditable(true);
        nacionalidade.setEditable(true);
        indentidade.setEditable(true);
        cpf.setEditable(true);
        dataNascimento.setEnabled(true);
        escolaridade.setEditable(true);
        instituicao.setEditable(true);
        telefoneFixo.setEditable(true);
        celular.setEditable(true);
        email.setEditable(true);
        rua.setEditable(true);
        numero.setEditable(true);
        bairro.setEditable(true);
        cidade.setEditable(true);
        complemento.setEditable(true);
        cep.setEditable(true);
        categoria.setEditable(true);
        nomeEmpresario.setEditable(true);
        posicao.setEditable(true);
        peso.setEditable(true);
        altura.setEditable(true);
        sexo.setEnabled(true);
        pais.setEnabled(true);
        estado.setEnabled(true);

    }//GEN-LAST:event_HabilitarCamposActionPerformed

    private void idPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new CadastroJogador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Contrato;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton HabilitarCampos;
    private javax.swing.JButton InformacoesMedicas;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField altura;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField complemento;
    private javax.swing.JTextField cpf;
    private javax.swing.JFormattedTextField dataNascimento;
    private javax.swing.JTextField dddCelular;
    private javax.swing.JTextField dddFixo;
    private javax.swing.JTextField email;
    private javax.swing.JTextField escolaridade;
    private javax.swing.JComboBox estado;
    private javax.swing.JTextField idPessoa;
    private javax.swing.JTextField indentidade;
    private javax.swing.JTextField instituicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nacionalidade;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomeEmpresario;
    private javax.swing.JTextField numero;
    private javax.swing.JComboBox<String> pais;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField posicao;
    private javax.swing.JTextField rua;
    private javax.swing.JComboBox sexo;
    private javax.swing.JTextField sobreNome;
    private javax.swing.JTextField telefoneFixo;
    // End of variables declaration//GEN-END:variables
}
